mystr="guvi is the Best Learning platform"
print(mystr)
print(mystr.upper())
print(mystr.lower())
print(mystr.count('a'))
print(mystr.count('the'))
print(mystr.find('the'))
print(mystr.replace('Best',"Excellent"))
print(mystr.startswith("Guvi"))
print(mystr.endswith("Best"))
print(mystr.capitalize())
data=mystr.split()
print(data)